[0m19:01:13.994531 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f98d8627e20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f98f8788be0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f98f879b8b0>]}


============================== 19:01:13.998270 | 9c6724a3-b9cf-4c03-bc16-e7c80126d34b ==============================
[0m19:01:13.998270 [info ] [MainThread]: Running with dbt=1.7.6
[0m19:01:13.999021 [debug] [MainThread]: running dbt with arguments {'write_json': 'True', 'version_check': 'True', 'printer_width': '80', 'partial_parse': 'True', 'invocation_command': 'dbt init northwinds_dbt', 'target_path': 'None', 'log_cache_events': 'False', 'indirect_selection': 'eager', 'use_experimental_parser': 'False', 'profiles_dir': '/Users/talmihaela92/.dbt', 'log_format': 'default', 'use_colors': 'True', 'fail_fast': 'False', 'send_anonymous_usage_stats': 'True', 'debug': 'False', 'log_path': 'logs', 'cache_selected_only': 'False', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'warn_error': 'None', 'static_parser': 'True', 'introspect': 'True', 'no_print': 'None'}
[0m19:01:13.999700 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse dict {'dir': PosixPath('/Users/talmihaela92/.dbt')}
[0m19:01:14.000127 [info ] [MainThread]: Creating dbt configuration folder at 
[0m19:01:14.001221 [debug] [MainThread]: Starter project path: /Users/talmihaela92/Desktop/de-class/DBT/dbt-core-setup-northwinds/codebase/venv/lib/python3.8/site-packages/dbt/include/starter_project
[0m19:01:14.004615 [info ] [MainThread]: 
Your new dbt project "northwinds_dbt" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m19:01:14.005074 [info ] [MainThread]: Setting up your profile.
[0m19:01:22.280854 [error] [MainThread]: Encountered an error:

[0m19:01:22.283889 [error] [MainThread]: Traceback (most recent call last):
  File "/Users/talmihaela92/Desktop/de-class/DBT/dbt-core-setup-northwinds/codebase/venv/lib/python3.8/site-packages/dbt/cli/requires.py", line 91, in wrapper
    result, success = func(*args, **kwargs)
  File "/Users/talmihaela92/Desktop/de-class/DBT/dbt-core-setup-northwinds/codebase/venv/lib/python3.8/site-packages/dbt/cli/requires.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/Users/talmihaela92/Desktop/de-class/DBT/dbt-core-setup-northwinds/codebase/venv/lib/python3.8/site-packages/dbt/cli/main.py", line 515, in init
    results = task.run()
  File "/Users/talmihaela92/Desktop/de-class/DBT/dbt-core-setup-northwinds/codebase/venv/lib/python3.8/site-packages/dbt/task/init.py", line 344, in run
    self.setup_profile(profile_name)
  File "/Users/talmihaela92/Desktop/de-class/DBT/dbt-core-setup-northwinds/codebase/venv/lib/python3.8/site-packages/dbt/task/init.py", line 263, in setup_profile
    adapter = self.ask_for_adapter_choice()
  File "/Users/talmihaela92/Desktop/de-class/DBT/dbt-core-setup-northwinds/codebase/venv/lib/python3.8/site-packages/dbt/task/init.py", line 244, in ask_for_adapter_choice
    numeric_choice = click.prompt(prompt_msg, type=click.INT)
  File "/Users/talmihaela92/Desktop/de-class/DBT/dbt-core-setup-northwinds/codebase/venv/lib/python3.8/site-packages/click/termui.py", line 164, in prompt
    value = prompt_func(prompt)
  File "/Users/talmihaela92/Desktop/de-class/DBT/dbt-core-setup-northwinds/codebase/venv/lib/python3.8/site-packages/click/termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m19:01:22.289071 [debug] [MainThread]: Resource report: {"command_name": "init", "command_wall_clock_time": 8.318575, "process_user_time": 1.812462, "process_kernel_time": 0.129916, "process_mem_max_rss": "100282368", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m19:01:22.290896 [debug] [MainThread]: Command `dbt init` failed at 19:01:22.290114 after 8.32 seconds
[0m19:01:22.292149 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f98d8627e20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f98e8dbb4f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f98e8dbbc40>]}
[0m19:01:22.293085 [debug] [MainThread]: Flushing usage events
